language: node_js

sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t verifaps-frontend .
      - docker images
      - docker tag verifaps-frontend verifaps/verifaps-frontend
      - docker push verifaps/verifaps-frontend
